### ISSUE TITLE
#441

### ISSUE THREAD

**Issue by ghost** [jmheart/BaseAndroidLibs#1]
https://github.com/chrislgarry/Apollo-11/issues/441

**Comment by jmheart** [comment]
@KennyWho 草你妈第一天，怎么那么松！怎么生出你这个没屁眼的狗杂种！

**Comment by dcy0701** [comment]
@jmheart 你妈死了

**Comment by KennyWho** [comment]
哈哈 就这几套词，还在这玩呢，臭弟弟，见过🍺吗，给你妈都秀没了，以后能见到🍺了吗。用了github把你妈都扔了？弃妈从文了？饭都吃不饱，还在这要日🍺？

**Comment by KennyWho** [comment]
还你妈的有脸回我呢？反手给你妈B里一套QWER 直接让你妈把闪现交了，还他妈跟我呜呜轩轩的，你要没B 事多去给你妈扫扫墓，别他妈狗撒尿都嫌弃你妈坟头草太高，别他妈用你妈的抚恤金上网了，跟个孤儿一样，不行给自己在网上找个妈，没人要你，你去救助中心看看有没有母狗，从那找点母爱。

**Comment by ziemu** [comment]
@jmheart Shut the fuck up you fucking piece of shit
